### ISSUE TITLE
RSS Tracker newsblur无法授权

### ISSUE THREAD

**Issue by LimnN** [Richasy/AppCenter#16]
单独授权newsblur一直不成功，授权inoreader之后再在设置里面授权newsblur，提示操作失败

**Comment by Richasy** [comment]
你是否翻墙并解除了应用的本地网络环回？

**Comment by LimnN** [comment]
> 你是否翻墙并解除了应用的本地网络环回？

当然，我可以登录newsblur也能到nuewsblur的授权页面，但是点击授权之后授权图标转两圈之后RSS Tracker提示操作失败。

**Comment by Richasy** [comment]
OK，已经注意到了这个问题，稍后的更新中会进行修复
